<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Page not found at /download_pdf/0/</title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
    pre.exception_value { font-family: sans-serif; color: #575757; font-size: 1.5em; margin: 10px 0 10px 0; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Page not found <span>(404)</span></h1>
    <pre class="exception_value">No Blob matches the given query.</pre>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td>GET</td>
      </tr>
      <tr>
        <th>Request URL:</th>
        <td>http://localhost:8000/download_pdf/0/</td>
      </tr>
      
      <tr>
        <th>Raised by:</th>
        <td>mentoris.views.download_pdf</td>
      </tr>
      
    </table>
  </div>
  <div id="info">
    
      <p>
      Using the URLconf defined in <code>mentoris.urls</code>,
      Django tried these URL patterns, in this order:
      </p>
      <ol>
        
          <li>
            
                admin/
                
            
          </li>
        
          <li>
            
                mentapp/
                
            
          </li>
        
          <li>
            
                katex/
                [name='katex']
            
          </li>
        
          <li>
            
                login/
                [name='login']
            
          </li>
        
          <li>
            
                signUp/
                [name='sign_up']
            
          </li>
        
          <li>
            
                profile/
                [name='profile']
            
          </li>
        
          <li>
            
                profile/&lt;uuid:user_id&gt;/
                [name='user_info']
            
          </li>
        
          <li>
            
                profile/edit/&lt;uuid:user_id&gt;/
                [name='user_edit']
            
          </li>
        
          <li>
            
                main/
                [name='main']
            
          </li>
        
          <li>
            
                main/&lt;int:volume_id&gt;/
                [name='main_vol_chap']
            
          </li>
        
          <li>
            
                main/&lt;int:volume_id&gt;/&lt;chapter_id&gt;/
                [name='chapter']
            
          </li>
        
          <li>
            
                download_pdf/&lt;int:blob_key&gt;/
                [name='download_pdf']
            
          </li>
        
      </ol>
      <p>
        
          The current path, <code>download_pdf/0/</code>,
        
        matched the last one.
      </p>
    
  </div>

  <div id="explanation">
    <p>
      Youâ€™re seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 404 page.
    </p>
  </div>
</body>
</html>
